### ISSUE TITLE
No Make Rule for dx-tests

### ISSUE THREAD

**Issue by arky** [joneschrisg/android-build#5]
make[1]: **\* No rule to make target `out/host/linux-x86/framework/dx.jar', needed by`out/host/linux-x86/obj/EXECUTABLES/dx-tests_intermediates/dx-tests'.  Stop.
make[1]: **\* Waiting for unfinished jobs....
make[1]: Leaving directory `/home/arky/src/B2G/glue/gonk'

**Comment by arky** [comment]
$ make -d cts 
....
Reaping winning child 0x0d367b80 PID 14837 
Live child 0x0d367b80 (out/target/product/generic/symbols/system/lib/libctsverifier_jni.so) PID 14838 
build/tools/apriori/prelinkmap.c(168): library 'libctsverifier_jni.so' not in prelink map
Reaping losing child 0x0d367b80 PID 14838 
make: **\* [out/target/product/generic/symbols/system/lib/libctsverifier_jni.so] Error 1
Removing child 0x0d367b80 PID 14838 from chain.

**Comment by arky** [comment]
Need to add this library to libctsverifier_jni.so to prelink-linux-arm.map

**Comment by arky** [comment]
@cgjones Can you please help me add this library to the prelink file.

**Comment by joneschrisg** [comment]
The cts directory should have been removed.  What does |git status| say when you run it from the top-level b2g/ directory?

**Comment by arky** [comment]
Purging it from my source
